### ISSUE TITLE
Having trouble creating docc archive for STKAudioKit

### ISSUE THREAD

**Issue by aure** [AudioKit/docgen#2]
I added STKAudioKit to the generate script but it didn't work. I believe the script cannot handle C sources, as none of the repos added so far were anything but Swift. This will be important for all the AudioKit DSP libraries.

I got errors that looked like this:

```
In file included from <built-in>:1:
In file included from /Users/aurelius/Developer/AudioKit/docgen/.build/arm64-apple-macosx/debug/Stk.build/DerivedSources/resource_bundle_accessor.h:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected unqualified-id
@class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[2/95] Compiling DebugDSP.c
error: unspecified("fatalError")
```

**Comment by bdrelling** [comment]
Hmm, the script is just calling [`swift-docc-plugin`](https://github.com/apple/swift-docc-plugin), so it's definitely not the script. I would look into whether or not the DocC plugin can handle C libraries.

It looks like Swift Package Index isn't able to leverage `STKAudioKit`'s [`.spi.yml`](https://github.com/AudioKit/STKAudioKit/blob/main/.spi.yml) for documentation generation either. If SPI can't generate it, then we likely won't be able to, either.

Worst case scenario, we may need to use `xcodebuild docbuild` instead, or attempt to use `swift-docc` directly -- just more steps involved that would be annoying for maintenance. I spent a lot of time deciding between all three methods and the `swift-docc-plugin` is the most foolproof.

If you're able to generate the `.doccarchive` for C libraries otherwise, then you can just generate them via Xcode or whatever and manually move them into the `audiokit.io` repository. Not as sexy of an automated process, but that's the route I'd take for now -- especially if these libraries don't change super often.

**Comment by aure** [comment]
I tried the manual route but the website just showed a blank screen for STKAudioKit once I clicked into it. The .spi.yml file I thought was just there for swift package index. It doesn't cause any problem for PianoRoll which has it too.

**Comment by bdrelling** [comment]
> I tried the manual route but the website just showed a blank screen for STKAudioKit once I clicked into it.

Makes sense actually -- when you export a `.doccarchive` it doesn't use a `--hosting-base-path` by default. I'm not sure what the best option is.

What happens when you run `xcodebuild docbuild` for `STKAudioKit`? There are some instructions [here](https://developer.apple.com/documentation/xcode/distributing-documentation-to-external-developers) with a command you can run that would look something like this:

```sh
xcodebuild docbuild -scheme SlothCreator -derivedDataPath ~/Desktop/SlothCreatorBuild
```

Try running that in a C repository using DocC and see if it works. If _that_ doesn't work, then your next best bet is to dig into the DocC repo, maybe post an issue/discussion, not sure.

> The .spi.yml file I thought was just there for swift package index. It doesn't cause any problem for PianoRoll which has it too.

Right, it's definitely not a problem, but what I'm saying is that `STKAudioKit`'s [.spi.yml](https://github.com/AudioKit/STKAudioKit/blob/main/.spi.yml) is configured to product documentation on Swift Package Index.

Like, if it worked, it would be adding a button like this:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/3022693/186501562-3b66a680-9ace-4c4e-b85e-c825a77f00d7.png">

If I look at [STKAudioKit on SPI](https://swiftpackageindex.com/AudioKit/STKAudioKit), there's no Documentation link, which implies that SPI was unable to generate the documentation. You can see it [works for PianoRoll](https://swiftpackageindex.com/AudioKit/PianoRoll).

If SPI can't generate the documentation for STKAudioKit, then the `docgen` repo definitely won't be able to either -- both systems use the same underlying `swift-docc` tool and I'm positive SPI is more resilient towards it.

That make sense?

**Comment by aure** [comment]
This incantation builds but when I copy the .doccarchive it produce does not show up in the browser
```xcodebuild docbuild -scheme STKAudioKit -derivedDataPath BuildFolder -destination name="iPhone 8"```

The good news is that it compiles fine, just the output is somehow not compatible.
